ignorePatterns:
  - pattern: '^https://fheorg.substack.com/'
aliveStatusCodes:
  - 200
  - 206
  - 400
  - 503
dirs:
  - .
useGitIgnore: true
excludedFiles:
 - code-of-conduct.md
excludedDirs:
  - history/src
